# Generated by Django 5.2.5 on 2025-09-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.PositiveIntegerField()),
                ('dealer', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('vulnerability', models.CharField(choices=[('None', 'None'), ('NS', 'NS'), ('EW', 'EW'), ('Both', 'Both')], max_length=20)),
                ('hands', models.JSONField(default=dict)),
                ('auction_history', models.JSONField(default=list)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='game.session')),
            ],
            options={
                'ordering': ['deal_number'],
                'unique_together': {('session', 'deal_number')},
            },
        ),
    ]
