# Generated by Django 5.2.5 on 2025-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_bidcomment_userbiddingsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_deals',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='session',
            name='seed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
