# Generated by Django 5.2.5 on 2025-09-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_forkdeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, help_text='Space-separated bidding history')),
                ('seat_to_act', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('divergence', models.BooleanField(default=False, help_text='True if partners diverge at this node')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='game.deal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(help_text="The call made (e.g., '1H', 'P', 'X')", max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='game.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['deal', 'history'], name='game_node_deal_id_a70932_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['session', 'deal'], name='game_node_session_a4fdb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('deal', 'history', 'seat_to_act')},
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['node', 'call'], name='game_respon_node_id_1dd78f_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['user', 'node'], name='game_respon_user_id_3c2a18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('node', 'user')},
        ),
    ]
