# Generated by Django 5.2.5 on 2025-10-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_node_response_node_game_node_deal_id_a70932_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_call', models.CharField(help_text='The call that was superseded', max_length=10)),
                ('action', models.CharField(choices=[('REWIND', 'Rewind'), ('ADMIN', 'Admin Action'), ('MERGE', 'Merge')], help_text='Type of action performed', max_length=20)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
            ],
            options={
                'ordering': ['-action_timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='response',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when rewound past this response'),
        ),
        migrations.AddField(
            model_name='response',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='When this response was superseded', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='superseded_by_action',
            field=models.CharField(blank=True, choices=[('REWIND', 'Rewind'), ('ADMIN', 'Admin Action'), ('MERGE', 'Merge')], help_text='Why this response was superseded', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['is_active'], name='game_respon_is_acti_a9fd81_idx'),
        ),
        migrations.AddField(
            model_name='responseaudit',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_audits', to='game.deal'),
        ),
        migrations.AddField(
            model_name='responseaudit',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='game.node'),
        ),
        migrations.AddField(
            model_name='responseaudit',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='game.response'),
        ),
        migrations.AddField(
            model_name='responseaudit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_audits', to='game.session'),
        ),
        migrations.AddField(
            model_name='responseaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='responseaudit',
            index=models.Index(fields=['user', 'session', 'deal'], name='game_respon_user_id_82e585_idx'),
        ),
        migrations.AddIndex(
            model_name='responseaudit',
            index=models.Index(fields=['action_timestamp'], name='game_respon_action__5f9128_idx'),
        ),
    ]
