# Generated by Django 5.2.5 on 2025-10-03 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_responseaudit_alter_response_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text="User's comment on this divergence node")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_comments', to='game.deal')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game.node')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_comments', to='game.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['node', 'user'], name='game_nodeco_node_id_f4a2e7_idx'), models.Index(fields=['session', 'deal'], name='game_nodeco_session_9ed634_idx')],
                'unique_together': {('node', 'user')},
            },
        ),
    ]
