# Generated by Django 5.2.5 on 2025-10-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_nodecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
