# Generated by Django 5.2.5 on 2025-10-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='depth',
            field=models.IntegerField(default=0, help_text='Number of calls from root'),
        ),
        migrations.AddField(
            model_name='node',
            name='who_needs',
            field=models.CharField(default='both', help_text="Which users need to answer: 'both', 'creator', 'partner', or 'none'", max_length=20),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(help_text="The call made (e.g., '1H', 'P', 'X')", max_length=10)),
                ('by_set', models.JSONField(default=list, help_text="List of user roles: ['creator'], ['partner'], or ['creator','partner']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='game.deal')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='game.node')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='game.session')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='game.node')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'deal'], name='game_edge_session_8ef309_idx'), models.Index(fields=['from_node'], name='game_edge_from_no_4a04ab_idx')],
                'unique_together': {('session', 'deal', 'from_node', 'call')},
            },
        ),
    ]
